### ISSUE TITLE
Error when building docker image on Windows OS: "No hypervisor is present on this system."

### ISSUE THREAD

**Issue by KevinGouji** [NileshGule/AKS-learning-series#2]
![whatsapp image 2018-11-15 at 5 14 57 pm](https://user-images.githubusercontent.com/17694828/48988421-647f0300-f160-11e8-9c95-ba2623ed28fb.jpeg)

**Comment by KevinGouji** [comment]
This is because the windows feature Hyper-V is disabled. By enabling it, it should work well. [Here](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v) is the link of how to enable the Hyper-V feature.

**Comment by KevinGouji** [comment]
For running docker on windows OS, it will be better switch the docker daemon to Linux containers instead of windows containers.

**Comment by NileshGule** [comment]
thanks @KevinGouji for highlighting the issue and the resolution to fix the issue.
