### ISSUE TITLE
Failed to pull image "rahulsahay19/aksweb": rpc error: code = Unknown desc = Error response from daemon: manifest for rahulsahay19/aksweb:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by rahulsahay19** [NileshGule/AKS-learning-series#6]
Hi,

After creating AKS Resource group. Done the deployment. And then, when I am browsing with browse script, its saying unable to pull image as manifest is missing.

![image](https://user-images.githubusercontent.com/3886381/61588544-ed98ed80-abba-11e9-8d1a-7a0dd9c498da.png)

Is there anything I am missing here. Also, due to some installation issues, I haven't used minikube. Rather than that, I have used Kubernetes option from docker settings. I am also running on windows machine.

Thanks,
Rahul

**Comment by NileshGule** [comment]
@rahulsahay19 you are trying to pull an image from container registry with the **latest** tag. Your registry does not contain an image with this tag. Please push an image to Dockerhub with the latest tag or use the tag which is already existing in the container registry.

<img width="768" alt="docker latest tag image" src="https://user-images.githubusercontent.com/1298374/61834544-f3d4e580-aeaa-11e9-9f78-d1933e93abd3.PNG">

**Comment by rahulsahay19** [comment]
Yeah. Thanks. I forgot to close this ticket that day. Thanks for the update.
